### ISSUE TITLE
Proton mail security key implementation support passkey

### ISSUE THREAD

**Issue by hisgarden** [passkeydeveloper/discussions#3]
### Service Name

ProtonMail

### Service URL

mail.proton.me

### Terminology

- [ ] Using passkey terminology

### Icon

- [ ] Using passkey icon

### Autofill - Web

- [ ] Supported

### Autofill - Android

- [ ] Supported

### Autofill - iOS

- [ ] Supported

### Contact

- [ ] I am

### Additional Information

Insert a security key linked to your Proton Account.

**Comment by timcappalli** [comment]
@hisgarden, I believe ProtonMail only supports a security key as second factor, correct?

**Comment by timcappalli** [comment]
I just created an account to test, and confirmed these are second factor only.

**Comment by okonon** [comment]
@timcappalli i think the issue author is referring to allowing the use of Passkeys as a security key for 2FA. I am experienceing this as well. Basically Proton allows users to add Passkey (as well as as USB security keys) in Brave/Chrome:
1. Click Settings > Account and password > Security key toggle
2. Click "Try another way" button on Brave/Chrome's "Create a passkey for proton.me":
<img width="716" alt="Screenshot 2022-12-20 at 10 28 33" src="https://user-images.githubusercontent.com/1832398/208704170-fff4d44e-f866-445d-8984-6b9434473216.png">
4. "Choose how you want to create a passkey for proton.me" view will be shown.
<img width="490" alt="Screenshot 2022-12-20 at 10 25 52" src="https://user-images.githubusercontent.com/1832398/208704853-3cd74596-4c7a-4c94-93a2-95379a950f5b.png">
3. click "A different device" button.
4. Add passkey to different device like an iPhone.
5. Log out.
6. Attempt to sign in again.
7. After entering username/pass 2FA Proton page will be shown only showing USB option (there is no way to choose "other device"):
<img width="458" alt="Screenshot 2022-12-20 at 10 19 48" src="https://user-images.githubusercontent.com/1832398/208705487-966e1df3-2014-4749-8e32-1ae4b829f4e8.png">

Expected result is to choose "other device" and use previously used passkey stored on an iPhone.

Github supports this on Brave/Chrome when logging in:
1. Login to github with usename/pass
2. "Two-factor authentication" GitHub page will be shown, click "Use security key" button.
<img width="496" alt="Screenshot 2022-12-20 at 10 40 22" src="https://user-images.githubusercontent.com/1832398/208706634-b03e7dbf-c022-41f5-8488-a67fcd583001.png">
3. "Use your passkey" dialog with "A different device" will be shown allowing use to login with passkey stored on a phone:
<img width="706" alt="Screenshot 2022-12-20 at 10 40 38" src="https://user-images.githubusercontent.com/1832398/208707013-5f057f78-7160-4fb8-8e1c-8466837f4952.png">

Judging by GitHub's url i think it works on github because they use WebAuth. So the question is does/will Proton support WebAuth standard for 2FA?

Thanks guys you are doing awesome job!!!!
